var express = require('express');
var router = express.Router();
var jwt = require('jsonwebtoken');
var fs = require('fs');

         // keys generated by https://8gwifi.org/rsafunctions.jsp
    // the algorithm is set to RS256
  // Private Key - key must read in as utf8
  const RSA_PRIVATE_KEY = fs.readFileSync('./private.key', 'utf8');

router.get('/api/login', loginRoute);
router.post('/api/login', loginRoute);

function loginRoute(req, res) {
    console.log('login router called')
    const email = req.body.email,
    password = req.body.password;

    if (true) {
    //if (validateEmailAndPassword()) {
    //   const userId = findUserIdForEmail(email);

        var payload = { };
        payload.field01 = "Data 01";

        var signOptions =  {
          algorithm: 'RS256',
          expiresIn: '1h',
          subject: '1000'
      };

        console.log('private key: ' + RSA_PRIVATE_KEY);

        var jwtBearerToken = jwt.sign(JSON.stringify({ data: 'bar', expiresIn: 120, subject: '1000' }), RSA_PRIVATE_KEY);

        console.log('Token: ' + jwtBearerToken)

          // send the JWT back to the user in http request (with timestamp)
          
          res.status(200).json({
            idToken: jwtBearerToken, 
            expiresIn: 50
          });

         // res.cookie("SESSIONID", jwtBearerToken, {httpOnly:true, secure:true});
    }
    else {
        // send status 401 Unauthorized
        res.sendStatus(401); 
    }
}
module.exports = router;
